import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LeftNavBar from "./Components/LeftNavBar";
import TopNavBar from "./Components/TopNavBar";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Namaa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="min-h-screen flex">
            {/* Left Navigation Bar */}
            <LeftNavBar />
            {/* Main Content Area */}
            <div className="flex-1 ml-56 bg-slate-100 dark:bg-gray-900">
              {/* Top Navigation Bar */}
              <TopNavBar />
              {/* Page Content */}
              <main className="p-6 bg-b">{children}</main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
